# Generated by Django 6.0.5 on 2026-07-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
