# Generated by Django 6.0.5 on 2026-07-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('offers', '0002_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='offers', to='category.category'),
        ),
    ]
