# Generated by Django 6.0.5 on 2026-06-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('returned', 'Returned')], default='active', max_length=20),
        ),
    ]
