# Generated by Django 6.0.5 on 2026-07-16 (manually extended with data migration)

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_addresses(apps, schema_editor):
    """
    For every existing Order, copy its linked Address fields into a new
    OrderAddress row, then update the order's address_id to point at
    the new snapshot row.

    Uses raw SQL to avoid FK constraint errors caused by orders whose
    original address has already been deleted.

    NOTE: The old FK constraints on orders_order and orders_return must
    already be dropped before this function is called.
    """
    from django.db import connection

    OrderAddress = apps.get_model('orders', 'OrderAddress')

    # --- Orders ---
    # LEFT JOIN so orphaned orders (already-deleted address) still appear.
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT
                o.id                AS order_id,
                COALESCE(a.full_name, 'Unknown')        AS full_name,
                COALESCE(a.phone_number, '0000000000')  AS phone_number,
                COALESCE(a.address, '')                  AS address,
                COALESCE(a.city, 'Unknown')              AS city,
                COALESCE(a.state, 'Unknown')             AS state,
                COALESCE(a.postal_code, '000000')        AS postal_code,
                COALESCE(a.country, 'India')             AS country,
                COALESCE(a.address_type, 'HOME')         AS address_type
            FROM orders_order o
            LEFT JOIN addresses_address a ON a.id = o.address_id
        """)
        rows = cursor.fetchall()

    for (order_id, full_name, phone_number, address,
         city, state, postal_code, country, address_type) in rows:

        snapshot = OrderAddress.objects.create(
            full_name=full_name,
            phone_number=phone_number,
            address=address,
            city=city,
            state=state,
            postal_code=postal_code,
            country=country,
            address_type=address_type,
        )
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE orders_order SET address_id = %s WHERE id = %s",
                [snapshot.pk, order_id]
            )

    # --- Returns with a pickup_address ---
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT
                r.id                AS return_id,
                COALESCE(a.full_name, 'Unknown')        AS full_name,
                COALESCE(a.phone_number, '0000000000')  AS phone_number,
                COALESCE(a.address, '')                  AS address,
                COALESCE(a.city, 'Unknown')              AS city,
                COALESCE(a.state, 'Unknown')             AS state,
                COALESCE(a.postal_code, '000000')        AS postal_code,
                COALESCE(a.country, 'India')             AS country,
                COALESCE(a.address_type, 'HOME')         AS address_type
            FROM orders_return r
            JOIN addresses_address a ON a.id = r.pickup_address_id
            WHERE r.pickup_address_id IS NOT NULL
        """)
        ret_rows = cursor.fetchall()

    for (return_id, full_name, phone_number, address,
         city, state, postal_code, country, address_type) in ret_rows:

        snapshot = OrderAddress.objects.create(
            full_name=full_name,
            phone_number=phone_number,
            address=address,
            city=city,
            state=state,
            postal_code=postal_code,
            country=country,
            address_type=address_type,
        )
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE orders_return SET pickup_address_id = %s WHERE id = %s",
                [snapshot.pk, return_id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0005_alter_return_status'),
    ]

    operations = [
        # Step 1: Create the OrderAddress snapshot table.
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
                ('country', models.CharField(default='India', max_length=100)),
                ('address_type', models.CharField(default='HOME', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        # Step 2: Drop the OLD FK constraints FIRST so we can freely update address_id
        #         values during the data migration without constraint violations.
        #         The old constraints may already reference deleted rows, which is the
        #         exact bug we are fixing.
        migrations.RunSQL(
            sql="""
                ALTER TABLE orders_order
                    DROP CONSTRAINT IF EXISTS orders_order_address_id_0daf897b_fk_addresses_address_id;
                DROP INDEX IF EXISTS orders_order_address_id_0daf897b;

                ALTER TABLE orders_return
                    DROP CONSTRAINT IF EXISTS orders_return_pickup_address_id_6ad0bb99_fk_addresses;
                DROP INDEX IF EXISTS orders_return_pickup_address_id_6ad0bb99;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 3: Data migration — snapshot existing address data into OrderAddress rows,
        #         then update order/return rows to point at the new snapshots.
        migrations.RunPython(backfill_order_addresses, migrations.RunPython.noop),

        # Step 4: Add new FK constraints pointing at orders_orderaddress.
        migrations.RunSQL(
            sql="""
                ALTER TABLE orders_order
                    ADD CONSTRAINT orders_order_address_id_fk_orderaddress
                    FOREIGN KEY (address_id)
                    REFERENCES orders_orderaddress(id)
                    NOT VALID;
                CREATE INDEX IF NOT EXISTS orders_order_address_id_idx
                    ON orders_order (address_id);

                ALTER TABLE orders_return
                    ADD CONSTRAINT orders_return_pickup_address_id_fk_orderaddress
                    FOREIGN KEY (pickup_address_id)
                    REFERENCES orders_orderaddress(id)
                    NOT VALID;
                CREATE INDEX IF NOT EXISTS orders_return_pickup_address_id_idx
                    ON orders_return (pickup_address_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 5: Update Django migration state so it knows about the new FK targets.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='address',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to='orders.orderaddress',
                    ),
                ),
                migrations.AlterField(
                    model_name='return',
                    name='pickup_address',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='orders.orderaddress',
                    ),
                ),
            ],
            database_operations=[],  # all DDL already done in RunSQL above
        ),
    ]
